/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    categories: Category
    'tech-stack': TechStack
    projects: Project
    'project-versions': ProjectVersion
    'blog-posts': BlogPost
    testimonials: Testimonial
    'contact-messages': ContactMessage
    'newsletter-subscribers': NewsletterSubscriber
    notifications: Notification
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    'tech-stack': TechStackSelect<false> | TechStackSelect<true>
    projects: ProjectsSelect<false> | ProjectsSelect<true>
    'project-versions': ProjectVersionsSelect<false> | ProjectVersionsSelect<true>
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>
    notifications: NotificationsSelect<false> | NotificationsSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    'site-settings': SiteSetting
    homepage: Homepage
    profile: Profile
    seo: Seo
    social: Social
    contact: Contact
    analytics: Analytics
  }
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>
    homepage: HomepageSelect<false> | HomepageSelect<true>
    profile: ProfileSelect<false> | ProfileSelect<true>
    seo: SeoSelect<false> | SeoSelect<true>
    social: SocialSelect<false> | SocialSelect<true>
    contact: ContactSelect<false> | ContactSelect<true>
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  /**
   * Accessible alternative text. Required for public images.
   */
  alt: string
  /**
   * Optional human-readable image caption.
   */
  caption?: string | null
  /**
   * Optional author, source, or attribution note.
   */
  credit?: string | null
  /**
   * Simple folder/group key, e.g. projects, blog, seo, homepage.
   */
  folder?: string | null
  tags?:
    | {
        label: string
        id?: string | null
      }[]
    | null
  /**
   * Allow this media item to be used on public pages.
   */
  isPublic?: boolean | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number
  title: string
  /**
   * URL-friendly identifier. Auto-generated from title when empty.
   */
  slug: string
  description?: string | null
  type: 'project' | 'blog' | 'tech-stack' | 'shared'
  /**
   * Optional parent category.
   */
  parent?: (number | null) | Category
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack".
 */
export interface TechStack {
  id: number
  name: string
  /**
   * Used as the icon key for AppIcon, e.g. nextjs, react, typescript.
   */
  slug: string
  /**
   * Short tooltip-friendly description.
   */
  description?: string | null
  /**
   * Optional brand color, e.g. #3178C6.
   */
  color?: string | null
  /**
   * Use categories with type "Tech Stack" or "Shared".
   */
  category?: (number | null) | Category
  /**
   * Official website URL.
   */
  officialUrl?: string | null
  /**
   * Official documentation URL.
   */
  documentationUrl?: string | null
  /**
   * Show in highlighted homepage sections.
   */
  featured?: boolean | null
  /**
   * Allow this technology to appear on public pages.
   */
  visible?: boolean | null
  sortOrder?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number
  title: string
  /**
   * URL-friendly identifier. Auto-generated from title when empty.
   */
  slug: string
  /**
   * Short project summary for cards, lists, and SEO previews.
   */
  excerpt: string
  /**
   * Short marketing line used in featured project previews. Keep it concise and outcome-focused.
   */
  cardTagline?: string | null
  description: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  /**
   * Primary image for project cards and list pages.
   */
  coverImage?: (number | null) | Media
  /**
   * Large visual for featured homepage/project sections.
   */
  featuredImage?: (number | null) | Media
  stage: 'idea' | 'planning' | 'development' | 'testing' | 'released' | 'maintenance' | 'archived'
  /**
   * Project completion percentage from 0 to 100.
   */
  progress?: number | null
  /**
   * Current public or internal version, e.g. 1.0.0.
   */
  currentVersion?: string | null
  /**
   * Show this project in featured sections.
   */
  isFeatured?: boolean | null
  publishedAt?: string | null
  startedAt?: string | null
  releasedAt?: string | null
  /**
   * Use categories with type "Project" or "Shared".
   */
  category?: (number | null) | Category
  /**
   * Technologies used in this project.
   */
  techStack?: (number | TechStack)[] | null
  /**
   * Articles related to this project.
   */
  relatedBlogPosts?: (number | BlogPost)[] | null
  github?: {
    /**
     * Public GitHub repository URL.
     */
    url?: string | null
    /**
     * GitHub owner or organization name.
     */
    owner?: string | null
    /**
     * GitHub repository name.
     */
    repo?: string | null
    /**
     * Allow frontend to fetch and show live GitHub stats.
     */
    showStats?: boolean | null
  }
  links?:
    | {
        label: string
        /**
         * If empty, frontend should show disabled CTA with "Невдовзі".
         */
        url?: string | null
        type: 'github' | 'live' | 'documentation' | 'case-study' | 'figma' | 'other'
        isEnabled?: boolean | null
        id?: string | null
      }[]
    | null
  gallery?:
    | {
        image: number | Media
        caption?: string | null
        alt: string
        sortOrder?: number | null
        isFeatured?: boolean | null
        deviceFrame: 'none' | 'desktop' | 'laptop' | 'tablet' | 'mobile'
        id?: string | null
      }[]
    | null
  highlights?:
    | {
        title: string
        description: string
        /**
         * Icon key for frontend icon mapping.
         */
        icon?: string | null
        id?: string | null
      }[]
    | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    ogImage?: (number | null) | Media
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number
  title: string
  /**
   * URL-friendly identifier. Auto-generated from title when empty.
   */
  slug: string
  /**
   * Short summary for blog cards, previews, and SEO snippets.
   */
  excerpt: string
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  coverImage?: (number | null) | Media
  status: 'draft' | 'published' | 'archived'
  publishedAt?: string | null
  author?: (number | null) | User
  /**
   * Use categories with type "Blog" or "Shared".
   */
  category?: (number | null) | Category
  /**
   * Optional project connected to this article or dev note.
   */
  relatedProject?: (number | null) | Project
  tags?:
    | {
        label: string
        /**
         * URL-friendly tag identifier. Auto-generated from label when empty.
         */
        slug: string
        id?: string | null
      }[]
    | null
  seo?: {
    metaTitle?: string | null
    metaDescription?: string | null
    ogImage?: (number | null) | Media
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-versions".
 */
export interface ProjectVersion {
  id: number
  project: number | Project
  /**
   * Version number or label, e.g. 1.0.0, Phase 2.2, MVP.
   */
  version: string
  title: string
  releaseDate?: string | null
  summary: string
  highlights?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  breakingChanges?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  isStable?: boolean | null
  /**
   * Marks the current visible project version.
   */
  isCurrent?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number
  name: string
  role?: string | null
  company?: string | null
  message: string
  avatar?: (number | null) | Media
  status: 'pending' | 'approved' | 'rejected'
  /**
   * Optional rating from 1 to 5.
   */
  rating?: number | null
  /**
   * Where this testimonial came from, e.g. website, LinkedIn, direct message.
   */
  source?: string | null
  approvedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number
  name: string
  email: string
  subject: string
  message: string
  status: 'new' | 'read' | 'archived'
  /**
   * Where this message came from, e.g. website, landing, contact-page.
   */
  source?: string | null
  archivedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number
  email: string
  status: 'active' | 'unsubscribed'
  source?: string | null
  subscribedAt: string
  unsubscribedAt?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number
  title: string
  message: string
  type: 'contact' | 'testimonial' | 'system'
  status: 'unread' | 'read' | 'archived'
  /**
   * Collection that generated this notification.
   */
  relatedCollection?:
    ('contact-messages' | 'testimonials' | 'projects' | 'blog-posts' | 'system') | null
  /**
   * Payload document ID associated with this notification.
   */
  relatedDocumentId?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
    | ({
        relationTo: 'media'
        value: number | Media
      } | null)
    | ({
        relationTo: 'categories'
        value: number | Category
      } | null)
    | ({
        relationTo: 'tech-stack'
        value: number | TechStack
      } | null)
    | ({
        relationTo: 'projects'
        value: number | Project
      } | null)
    | ({
        relationTo: 'project-versions'
        value: number | ProjectVersion
      } | null)
    | ({
        relationTo: 'blog-posts'
        value: number | BlogPost
      } | null)
    | ({
        relationTo: 'testimonials'
        value: number | Testimonial
      } | null)
    | ({
        relationTo: 'contact-messages'
        value: number | ContactMessage
      } | null)
    | ({
        relationTo: 'newsletter-subscribers'
        value: number | NewsletterSubscriber
      } | null)
    | ({
        relationTo: 'notifications'
        value: number | Notification
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  caption?: T
  credit?: T
  folder?: T
  tags?:
    | T
    | {
        label?: T
        id?: T
      }
  isPublic?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  description?: T
  type?: T
  parent?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack_select".
 */
export interface TechStackSelect<T extends boolean = true> {
  name?: T
  slug?: T
  description?: T
  color?: T
  category?: T
  officialUrl?: T
  documentationUrl?: T
  featured?: T
  visible?: T
  sortOrder?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  cardTagline?: T
  description?: T
  coverImage?: T
  featuredImage?: T
  stage?: T
  progress?: T
  currentVersion?: T
  isFeatured?: T
  publishedAt?: T
  startedAt?: T
  releasedAt?: T
  category?: T
  techStack?: T
  relatedBlogPosts?: T
  github?:
    | T
    | {
        url?: T
        owner?: T
        repo?: T
        showStats?: T
      }
  links?:
    | T
    | {
        label?: T
        url?: T
        type?: T
        isEnabled?: T
        id?: T
      }
  gallery?:
    | T
    | {
        image?: T
        caption?: T
        alt?: T
        sortOrder?: T
        isFeatured?: T
        deviceFrame?: T
        id?: T
      }
  highlights?:
    | T
    | {
        title?: T
        description?: T
        icon?: T
        id?: T
      }
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        ogImage?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-versions_select".
 */
export interface ProjectVersionsSelect<T extends boolean = true> {
  project?: T
  version?: T
  title?: T
  releaseDate?: T
  summary?: T
  highlights?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  breakingChanges?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  isStable?: T
  isCurrent?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  content?: T
  coverImage?: T
  status?: T
  publishedAt?: T
  author?: T
  category?: T
  relatedProject?: T
  tags?:
    | T
    | {
        label?: T
        slug?: T
        id?: T
      }
  seo?:
    | T
    | {
        metaTitle?: T
        metaDescription?: T
        ogImage?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T
  role?: T
  company?: T
  message?: T
  avatar?: T
  status?: T
  rating?: T
  source?: T
  approvedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T
  email?: T
  subject?: T
  message?: T
  status?: T
  source?: T
  archivedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T
  status?: T
  source?: T
  subscribedAt?: T
  unsubscribedAt?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T
  message?: T
  type?: T
  status?: T
  relatedCollection?: T
  relatedDocumentId?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number
  siteName: string
  siteDescription: string
  logo?: (number | null) | Media
  defaultLanguage: 'en' | 'uk'
  /**
   * Temporarily hide the public website.
   */
  maintenanceMode?: boolean | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number
  hero: {
    eyebrow?: string | null
    title: string
    /**
     * Exact phrase inside the title that receives strong emphasis.
     */
    titleAccent?: string | null
    subtitle: string
    /**
     * Exact phrase inside the subtitle that receives accent emphasis.
     */
    subtitleAccent?: string | null
    primaryCtaLabel?: string | null
    primaryCtaUrl?: string | null
    secondaryCtaLabel?: string | null
    secondaryCtaUrl?: string | null
    image?: (number | null) | Media
  }
  currentMissionSection?: {
    enabled?: boolean | null
    eyebrow?: string | null
    /**
     * Optional custom title. Leave empty to use “Building {project title}”.
     */
    title?: string | null
    description?: string | null
    /**
     * Explicit project shown as the current mission. No automatic project fallback is used.
     */
    project?: (number | null) | Project
    ctaLabel?: string | null
    /**
     * Optional safe internal or HTTPS URL. When empty, the preferred enabled project link is used.
     */
    ctaUrlOverride?: string | null
    footerLabel?: string | null
    footerText?: string | null
  }
  /**
   * Selected projects for the homepage. If empty, frontend can fallback to featured projects.
   */
  featuredProjects?: (number | Project)[] | null
  /**
   * Selected technologies for the homepage skills section.
   */
  selectedTechStack?: (number | TechStack)[] | null
  testimonialsSection?: {
    enabled?: boolean | null
    title?: string | null
    description?: string | null
  }
  socialFeedsSection?: {
    enabled?: boolean | null
    title?: string | null
    description?: string | null
  }
  contactSection?: {
    enabled?: boolean | null
    eyebrow?: string | null
    title?: string | null
    /**
     * Exact phrase inside the title that receives accent emphasis.
     */
    titleAccent?: string | null
    description?: string | null
    formTitle?: string | null
    formDescription?: string | null
    footerLabel?: string | null
    footerText?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number
  name: string
  role: string
  location?: string | null
  status?: ('available' | 'focused' | 'unavailable') | null
  portrait?: (number | null) | Media
  shortBio?: string | null
  availability?: string | null
  /**
   * Used to derive the public years-of-experience metric.
   */
  careerStartedAt?: string | null
  /**
   * Optional fallback for the Hero secondary CTA.
   */
  cvFile?: (number | null) | Media
  /**
   * Optional manual public metrics. Derived collection and experience metrics stay in code.
   */
  metrics?:
    | {
        key: string
        label: string
        value: number
        suffix?: string | null
        enabled?: boolean | null
        id?: string | null
      }[]
    | null
  /**
   * Optional truthful activity note. Leave disabled until a manual note or live integration exists.
   */
  heroActivity?: {
    enabled?: boolean | null
    label?: string | null
    detail?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number
  defaultMetaTitle: string
  defaultMetaDescription: string
  defaultOgImage?: (number | null) | Media
  /**
   * Default robots behavior for public pages.
   */
  robots: 'index-follow' | 'noindex-follow' | 'noindex-nofollow'
  sitemapEnabled?: boolean | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social".
 */
export interface Social {
  id: number
  githubUrl?: string | null
  linkedinUrl?: string | null
  /**
   * Public Telegram profile or contact URL.
   */
  telegramUrl?: string | null
  /**
   * X / Twitter profile URL.
   */
  xUrl?: string | null
  instagramUrl?: string | null
  dribbbleUrl?: string | null
  youtubeUrl?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number
  email: string
  phone?: string | null
  location?: string | null
  /**
   * Enable or disable the public contact form.
   */
  contactFormEnabled?: boolean | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number
  /**
   * Enable or disable analytics on the public website.
   */
  enabled?: boolean | null
  /**
   * Google Analytics measurement ID, e.g. G-XXXXXXXXXX.
   */
  googleAnalyticsId?: string | null
  /**
   * Plausible Analytics domain, e.g. example.com.
   */
  plausibleDomain?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T
  siteDescription?: T
  logo?: T
  defaultLanguage?: T
  maintenanceMode?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T
        title?: T
        titleAccent?: T
        subtitle?: T
        subtitleAccent?: T
        primaryCtaLabel?: T
        primaryCtaUrl?: T
        secondaryCtaLabel?: T
        secondaryCtaUrl?: T
        image?: T
      }
  currentMissionSection?:
    | T
    | {
        enabled?: T
        eyebrow?: T
        title?: T
        description?: T
        project?: T
        ctaLabel?: T
        ctaUrlOverride?: T
        footerLabel?: T
        footerText?: T
      }
  featuredProjects?: T
  selectedTechStack?: T
  testimonialsSection?:
    | T
    | {
        enabled?: T
        title?: T
        description?: T
      }
  socialFeedsSection?:
    | T
    | {
        enabled?: T
        title?: T
        description?: T
      }
  contactSection?:
    | T
    | {
        enabled?: T
        eyebrow?: T
        title?: T
        titleAccent?: T
        description?: T
        formTitle?: T
        formDescription?: T
        footerLabel?: T
        footerText?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T
  role?: T
  location?: T
  status?: T
  portrait?: T
  shortBio?: T
  availability?: T
  careerStartedAt?: T
  cvFile?: T
  metrics?:
    | T
    | {
        key?: T
        label?: T
        value?: T
        suffix?: T
        enabled?: T
        id?: T
      }
  heroActivity?:
    | T
    | {
        enabled?: T
        label?: T
        detail?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  defaultMetaTitle?: T
  defaultMetaDescription?: T
  defaultOgImage?: T
  robots?: T
  sitemapEnabled?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_select".
 */
export interface SocialSelect<T extends boolean = true> {
  githubUrl?: T
  linkedinUrl?: T
  telegramUrl?: T
  xUrl?: T
  instagramUrl?: T
  dribbbleUrl?: T
  youtubeUrl?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  email?: T
  phone?: T
  location?: T
  contactFormEnabled?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  enabled?: T
  googleAnalyticsId?: T
  plausibleDomain?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
